[package]
name = "wallet_address_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
secp256k1 = { version = "0.28.0", features = ["rand"] }
rand = "0.8.5"
sha2 = "0.10.8"
ripemd = "0.1.3"
bs58 = "0.5.0"
hex = "0.4.3"
